spark-streaming {
  input-dir       = "images"
  output-dir      = "output"
  checkpoint-dir  = "checkpoints"
  simulator-interval-ms = 5000
  window-duration = "31 days"
  watermark-duration = "1 day"
}
